[flint]
name = "Orbh Workflow"

[shards]
installed = [
  { name = "flint", remote = "NUU-Cognition/shard-flint" },
  { name = "orbh", remote = "NUU-Cognition/shard-orbh" },
]
dev-remote = []
dev-local = []

[workspace]
repositories = [
  { name = "orbh-workflows", url = "https://github.com/NUU-Cognition/orbh-workflows.git" },
]
