[flint]
name = "Orbh Workflow"
type = "flint"

[shards]
flint = { source = "@nuucognition/flint", git = "NUU-Cognition/shard-flint" }
orbh = { source = "@nuucognition/orbh", git = "NUU-Cognition/shard-orbh" }
invironments = { source = "NUU-Cognition/shard-invironments" }

[workspace]
repositories = [
  { name = "orbh-workflows", url = "https://github.com/NUU-Cognition/orbh-workflows.git" },
  { name = "orbh-unified", url = "https://github.com/NUU-Cognition/orbh-unified.git" },
]
